# Generated by Django 4.1.2 on 2022-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_image_movie_published_at_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Frensh'), ('sp', 'Spanish'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('gr', 'German'), ('it', 'Italian')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
