# Generated by Django 4.1.2 on 2022-10-16 18:29

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=movie.models.Actor.image_upload)),
                ('wikipedia_url', models.URLField(max_length=250)),
            ],
        ),
    ]
