# Generated by Django 4.1.2 on 2022-10-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_actor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='slug',
        ),
    ]
