# Generated by Django 4.1.2 on 2022-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_actor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(max_length=255),
        ),
    ]
