# Generated by Django 4.1.2 on 2022-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_actor_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='his_movies', to='movie.movie'),
        ),
    ]
