# Generated by Django 4.1.2 on 2022-10-17 06:43

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('country', models.CharField(choices=[('US', 'US'), ('UK', 'UK'), ('Canada', 'Canada'), ('Japan', 'Jaban'), ('Kore', 'Kore'), ('Turkey', 'Turkey')], max_length=50)),
                ('image', models.ImageField(upload_to=movie.models.Series.image_upload)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('season_count', models.IntegerField()),
                ('epsoide_count', models.IntegerField()),
                ('producer', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Frensh'), ('sp', 'Spanish'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('gr', 'German'), ('it', 'Italian')], max_length=25)),
                ('actors', models.ManyToManyField(blank=True, null=True, related_name='series_actors', to='movie.actor')),
                ('type', models.ManyToManyField(related_name='series_type', to='movie.movietype')),
            ],
        ),
    ]
