# Generated by Django 4.1.2 on 2022-10-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('epsoide_count', models.ImageField(upload_to='')),
                ('production_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Epsoide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('trailer', models.URLField(max_length=255)),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epsoide_subtitle', to='movie.subtitle')),
            ],
        ),
    ]
