# Generated by Django 4.1.2 on 2022-10-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_season_epsoide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epsoide',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epsoide_subtitle', to='movie.subtitle'),
        ),
    ]
