# Generated by Django 4.1.2 on 2022-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_epsoide_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='seasons',
            field=models.ManyToManyField(related_name='Series_Seasons', to='movie.season'),
        ),
    ]
