# Generated by Django 4.1.2 on 2022-10-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_season_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='epsoides',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Season_Epsoides', to='movie.epsoide'),
            preserve_default=False,
        ),
    ]
