# Generated by Django 4.1.2 on 2022-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_season_epsoides'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='series',
            field=models.ManyToManyField(related_name='Played', to='movie.series'),
        ),
    ]
