# Generated by Django 4.1.2 on 2022-10-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_actor_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='his_movies', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actors', to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(related_name='series_actors', to='movie.actor'),
        ),
    ]
