# Generated by Django 4.1.2 on 2022-10-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_alter_actor_movies_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
