# Generated by Django 4.1.2 on 2022-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_movie_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='his_movies', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='Played', to='movie.series'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movie_actors', to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='movie_type', to='movie.movietype'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='Series', to='movie.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='series_actors', to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='series',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='Series_Seasons', to='movie.season'),
        ),
        migrations.AlterField(
            model_name='series',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='series_type', to='movie.movietype'),
        ),
    ]
