# Generated by Django 4.1.2 on 2022-10-21 10:46

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_alter_actor_movies_alter_actor_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='series',
        ),
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(max_length=255, upload_to=movie.models.Movie.image_upload),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(max_length=255, upload_to=movie.models.Series.image_upload),
        ),
    ]
