# Generated by Django 4.1.2 on 2022-10-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_remove_actor_movies_remove_actor_series_actor_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
