# Generated by Django 4.1.2 on 2022-10-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_movietype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='seasons',
        ),
    ]
