# Generated by Django 4.1.2 on 2022-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_remove_season_epsoides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ManyToManyField(related_name='Series', to='movie.series'),
        ),
    ]
