# Generated by Django 4.1.2 on 2022-10-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_alter_season_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='epsoide',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
