# Generated by Django 4.1.2 on 2022-10-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_epsoide_slug_season_slug_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='epsoide',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epsoide',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='movie.season'),
            preserve_default=False,
        ),
    ]
