# Generated by Django 4.1.2 on 2022-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0033_epsoide_rate_epsoide_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epsoide',
            name='trailer',
        ),
        migrations.AddField(
            model_name='season',
            name='trailer',
            field=models.URLField(default='https://www.youtube.com/watch?v=lz2d7MzgAnc&list=PLxIvc-MGOs6ib0oK1z9C46DeKd9rRcSMY&index=4', max_length=255),
            preserve_default=False,
        ),
    ]
