# Generated by Django 4.1.2 on 2022-10-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0034_remove_epsoide_trailer_season_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='epsoide_count',
            field=models.IntegerField(),
        ),
    ]
