# Generated by Django 4.1.2 on 2022-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0035_alter_season_epsoide_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epsoide',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
