# Generated by Django 4.1.2 on 2022-10-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0036_alter_epsoide_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Series', to='movie.series'),
        ),
    ]
